name: todo_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0-246.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.7

  #service locator
  get_it: ^8.0.3

  #dateFormat
  intl: ^0.20.2

  #Database
  shared_preferences: ^2.5.3
  floor: ^1.5.0

  #make request to api 
  retrofit: ^4.4.2

  #create random ID
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  floor_generator: ^1.4.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/fonts/
